### ISSUE TITLE
How to correctly get the area of subPolygon of a sphericalPolygon ?

### ISSUE THREAD

**Issue by felixveysseyre** [spacetelescope/spherical_geometry#107]
Hello,

I am computing the intersection of spherical polygons.
Sometime, these intersections result in more than one spherical polygon = the intersection contains multiple polygons.

To compute the area of these subPolygons, I have implemented the following method:
```
def displaySubPolygonArea(sphericalPolygon):

    pointsList = list(sphericalPolygon.points)
    insidePointList = list(sphericalPolygon.inside)

    for i in range(0, len(pointsList)):

        subSphericalPolygon = SphericalPolygon(pointsList[i], insidePointList[i], False)

        print(subSphericalPolygon.area())
```

Unfortunately, the are return is not always correct as the area printed is sometime very near 4*Pi.

Do you advise another way ?

Thanks

**Comment by bernie-simon** [comment]
Reverse the order of the points and take the absolute value of the area.

**Comment by mcara** [comment]
I am lost here. I know @mdboom explained the idea in  https://github.com/spacetelescope/spherical_geometry/issues/64 but in https://github.com/spacetelescope/spherical_geometry/issues/73 I raised the issue of a need for negative area and I though that you @bernie-simon fixed it in https://github.com/spacetelescope/spherical_geometry/pull/75 in which you say _"Modified area computation so that negative values are returned instead of values between two and four pi."_ What happened to that PR?

**Comment by pllim** [comment]
It was redone as #77 according to log.

**Comment by pllim** [comment]
@felixveysseyre , did Bernie sufficiently answer your question? If so, please close the issue. Thank you.

**Comment by felixveysseyre** [comment]
Well, looking at your answers it seems I should get an negative area instead of something between 2*Pi and 4*Pi.

Maybe I have misunderstood.

**Comment by bernie-simon** [comment]
Because a spherical polygon divides the sphere into two parts, the area is ambiguous. The definition of a polygon we use includes an interior point to help resolve the issue. The area returned is positive or negative depending on the ordering of the points. If they are clockwise with respect to the interior point the area is positive and if counter-clockwise, the area is negative. This is not something we explicitly programmed, it falls out of the formula we use. Other software we wrote which uses the spherical geometry package wants the area to sometimes be negative, otherwise I would "fix" the problem by taking the absolute value. 
If you are dealing with small polygons, less than a hemisphere in size, you jjust need to force the answer to be between 0 and 2*pi
If area < 0,

**Comment by bernie-simon** [comment]
# To force the area between 0 and 2 pi 
    If area < 0.0:
        area = abs(area)
    elif area > 2.0 * math.pi:
        area = 4.0 * math.pi - area

**Comment by felixveysseyre** [comment]
Ok. I thought you made some modifications to get area between -2Pi and +2Pi, that's why I was expecting a fix.

I will implement my own function therefore.

Thanks for your help @bernie-simon !

**Comment by mcara** [comment]
That is exactly what I was thinking as well and that was the reason I opened previous ticket on polygon area. Now I am confused with regard to
 issue #73 that I thought was fixed in PR #75(or #77). What was the point of these PRs?

**Comment by mcara** [comment]
From https://github.com/spacetelescope/spherical_geometry/pull/75#issue-153449452:

> Modified area computation so that negative values are returned instead of values between two and four pi.

Also see https://github.com/spacetelescope/spherical_geometry/pull/75/files#diff-ab7734d820b559d85f732ae44c9207a0R420 which, essentially, is the same as the code @bernie-simon  advises @felixveysseyre to use in https://github.com/spacetelescope/spherical_geometry/issues/107#issuecomment-316411383

So, important questions, in my opinion, are:

1. Does `spherical_geometry` allow polygons larger than half sphere?
2. Can area of a convex (for clarity) polygon smaller than 1/2 sphere be larger than 2*pi?

Since this package now is being used by more people than just myself, I believe it is important to fix the behavior of `area` and document exactly what is to be expected from this function. Area computation should not be ambiguous assuming inner point is being used to identify the polygon.

**Comment by bernie-simon** [comment]
First, the points in a spherical polygon are supposed to be in clockwise order. Clockwise is determined with respect to the interior point. To support this, polygon creation has the optional auto_orient keyword, which reverses the order of the points defining the polygon if they are counter-clockwise. If the points of the polygon are counter-clockwise, the area is changed to a negative value:

    # Return a negative area if the points in the polygon
    # are counter-clockwise
    if not self.is_clockwise():
        sum = sum - 4.0 * np.pi

The are of a polygon can be greater than 2 pi. It depends on the location of the interior point. If it is in the larger part of the sphere and the points of the polygon are ordered clockwise with respect to it, the polygon will be greater than 2 pi.

The determination that a polygon is clockwise or counter-clockwise can be ambiguous if the polygon is not convex. For the purposes of this library a polygon is ordered clockwise if the majority of the angle turnings are clockwise.

**Comment by bernie-simon** [comment]
As explained, the area of a spherical polygon depends critically on the ordering of the points in the polygon and the location of the interior point. We can't always expect the users of the library to get these right. If they don't and get the "wrong" area, they can force the result to the value between zero and two pi that they were expecting. That's all I intended with my previous comment.

**Comment by mcara** [comment]
@bernie-simon @felixveysseyre I understand all these explanations. However, I assume that @felixveysseyre  was using *small* polygons when he got areas close to ``4*pi`` which would be in disagreement with your statement:

> The are of a polygon can be greater than 2 pi. It depends on the location of the interior point. If it is in the larger part of the sphere and the points of the polygon are ordered clockwise with respect to it, the polygon will be greater than 2 pi.

...unless SphericalPolygon decides to compute the inner point to be "outside" the polygon during its initialization. How does the code decide where is the "inner point"? Does the result of the computation of the inner point depend on the orientation of the vertices of the polygon supplied to the initializer?

**Comment by bernie-simon** [comment]
The user can supply an inner point or not, it is optional. If no inner point is supplied, the code takes each set of three consecutive points and computes the angle between them. If this angle is less than pi (implying convexity) the code computes the midpoint between the first and third points, which should be inside the polygon. After computing all the midpoints it chooses the one which had the sharpest (smallest) angle between the three points. This is a heuristic and is not guaranteed to choose a point inside the polygon unless the polygon is convex.
The algorithm can fail to generate a point, most obviously if the polygon is a triangle. In this case it falls back on the older method of choosing the average of the vertexes.
The points should be in clockwise order, but by the definition that the code uses, clockwise is undefined unless you have an interior point. The user should have a sense of what clockwise is, which then determines whether the interior point is in the smaller or larger portion of the sphere.

**Comment by felixveysseyre** [comment]
I think I have understood @bernie-simon explanation correctly.

Let me add some information and maybe you would be able to tell me exactly where is the problem.

Using your library to compute the area of the following spherical-polygon, I got something near `4*pi`:
<img width="433" alt="capture d ecran 2017-07-19 a 22 01 23" src="https://user-images.githubusercontent.com/4909259/28387141-36ffbd92-6cce-11e7-9313-5f1895f62884.png">

This spherical-polygon has been computed using your library, using the intersections of the two following spherical-polygons:
<img width="537" alt="capture d ecran 2017-07-19 a 22 02 27" src="https://user-images.githubusercontent.com/4909259/28387188-6ad4d2ba-6cce-11e7-8328-bdd77541b09a.png">
<img width="404" alt="capture d ecran 2017-07-19 a 22 02 16" src="https://user-images.githubusercontent.com/4909259/28387187-6ad0e268-6cce-11e7-9a28-0e80918208b3.png">

These two polygons seems corrects and their inside points is represented by the two markers.

Following @bernie-simon explanations, I suspect that the inside point of the spherical-polygon intersection has not been correctly computed.

**Comment by mcara** [comment]
> I suspect that the inside point of the spherical-polygon intersection has not been correctly computed.

Ah! I see... So the problem appears to be in the computation of the inner point of an intersection...

**Comment by bernie-simon** [comment]
The code does not currently the computation of the interior point of an intersection well, because of the ambiguity I previously mentioned. I left the problem unsolved when I did the previous fixes to the auto_orient and interior point calculation. If inspiration hits me I'll revisit the question.

**Comment by felixveysseyre** [comment]
@bernie-simon Good to know where was the root cause !
